name: Run tests and publish Playwright report

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install
      
    - name: Run Playwright tests
      run: npm run test:headless

    - name: Upload Playwright report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./playwright-report
        publish_branch: gh-pages
